### ISSUE TITLE
天赋等级修复在皇冠绘制之后?

### ISSUE THREAD

**Issue by icarus-ai** [lianhong2758/kokomi-plugin#12]
[天赋等级修复](https://github.com/lianhong2758/kokomi-plugin/blob/c3257951d98e2690dc01d03ad61b54a87cb1c689/kokomi.go#L733)在[皇冠](https://github.com/lianhong2758/kokomi-plugin/blob/c3257951d98e2690dc01d03ad61b54a87cb1c689/kokomi.go#L716)绘制之后?

**Comment by lianhong2758** [comment]
> [天赋等级修复](https://github.com/lianhong2758/kokomi-plugin/blob/c3257951d98e2690dc01d03ad61b54a87cb1c689/kokomi.go#L733)在[皇冠](https://github.com/lianhong2758/kokomi-plugin/blob/c3257951d98e2690dc01d03ad61b54a87cb1c689/kokomi.go#L716)绘制之后?

天赋10级判断有没有给皇冠，要在修正之前进行

**Comment by icarus-ai** [comment]
> > [天赋等级修复](https://github.com/lianhong2758/kokomi-plugin/blob/c3257951d98e2690dc01d03ad61b54a87cb1c689/kokomi.go#L733)在[皇冠](https://github.com/lianhong2758/kokomi-plugin/blob/c3257951d98e2690dc01d03ad61b54a87cb1c689/kokomi.go#L716)绘制之后?
> 
> 天赋10级判断有没有给皇冠，要在修正之前进行

收到
