### ISSUE TITLE
获取kokomi配置文件错误，不能启动

### ISSUE THREAD

**Issue by wangfreexx** [lianhong2758/kokomi-plugin#20]
我编译了zbq，但是启动后显示 获取kokomi配置文件错误，环境是arm64

**Comment by lianhong2758** [comment]
是这样的，插件数据和源码是在一起的，编译就会出问题，所以要跑源码

**Comment by lianhong2758** [comment]
> 我编译了zbq，但是启动后显示 获取kokomi配置文件错误，环境是arm64

是这样的，插件数据和源码是在一起的，编译会找不到数据文件，所以要跑源码

**Comment by wangfreexx** [comment]
好的
